// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: price.proto
// Protobuf Java Version: 4.31.0

package com.example.demo;

@com.google.protobuf.Generated
public interface PriceUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.PriceUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string coin = 1;</code>
   * @return The coin.
   */
  java.lang.String getCoin();
  /**
   * <code>string coin = 1;</code>
   * @return The bytes for coin.
   */
  com.google.protobuf.ByteString
      getCoinBytes();

  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>double price = 3;</code>
   * @return The price.
   */
  double getPrice();
}
